papa = input("tell me birthday of papa")
mamma = input("tell me birthday of mamma")
pinku = input("tell me birthday of pinku")
bandercheeku = input("tell me birthday of bandercheeku")
sharol = input("tell me birthday of sharol")
print (mamma) 
print (papa)
print (pinku)
print (bandercheeku)
print (sharol)